[package]
name = "dnd-rs-desktop"
version.workspace = true
edition.workspace = true

[dependencies]
bevy.workspace = true
log.workspace = true
dnd-rs-plugin = { path = "../plugin" }

[[bin]]
name = "dnd"
path = "src/main.rs"
