[package]
name = "dnd-rs-level"
version.workspace = true
edition.workspace = true

[dependencies]
bevy.workspace = true
log.workspace = true
rand = "0.8.5"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "bench"
harness = false
