on: push

name: Build And Deploy for web

jobs:
  artifacts:
    name: Release for web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
      - name: Install wasm-pack
        run: npm install -g wasm-pack
      - name: Build
        run: wasm-pack build --target web --no-pack --no-typescript --release --out-dir assets/lib crates/web-app
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: d578b9ca3a384d53a33bf45006382347
          projectName: dnd
          directory: crates/web-app/assets
          wranglerVersion: "3"
